name: 'BoringCache Restore'
description: 'Cache once. Reuse everywhere. Restore cache artifacts from BoringCache (pair with boringcache/save).'
author: 'BoringCache'
inputs:
  cli-version:
    description: 'BoringCache CLI version (e.g., v1.0.0). Set to "skip" to disable automatic CLI setup.'
    required: false
    default: 'v1.5.0'
  workspace:
    description: 'Workspace identifier in format namespace/workspace (e.g., my-org/my-project). If not provided, uses repository name.'
    required: false
  entries:
    description: 'Cache entries in tag:path format (comma-separated for multiple)'
    required: false
  path:
    description: 'A list of files, directories, and wildcard patterns to restore (actions/cache compatible)'
    required: false
  key:
    description: 'An explicit key for restoring the cache (actions/cache compatible)'
    required: false
  restore-keys:
    description: 'An ordered list of prefix-matched keys for restoring stale cache'
    required: false
  # GitHub Actions specific features (handled at action level)
  enableCrossOsArchive:
    description: 'Enable cross-platform cache sharing by disabling automatic platform suffixes (translates to CLI --no-platform flag)'
    default: 'false'
    required: false
  enable-platform-suffix:
    description: 'Enable automatic platform suffix for tags (default: true)'
    default: 'true'
    required: false
  # CLI flags (passed directly to boringcache CLI)
  no-platform:
    description: 'Disable automatic platform suffix for tags (CLI --no-platform flag)'
    default: 'false'
    required: false
  fail-on-cache-miss:
    description: 'Fail the workflow if cache entry is not found (CLI --fail-on-cache-miss flag)'
    default: 'false'
    required: false
  lookup-only:
    description: 'Check cache entry existence without downloading (CLI --lookup-only flag)'
    default: 'false'
    required: false
  verbose:
    description: 'Enable detailed output (CLI --verbose flag)'
    default: 'false'
    required: false
outputs:
  cache-hit:
    description: 'A boolean value indicating an exact match was found for the primary key'
  cache-primary-key:
    description: 'The key of the cache entry that was restored'
  cache-matched-key:
    description: 'The key of the cache entry that was matched'
runs:
  using: 'node24'
  main: 'dist/restore-only/index.js'
branding:
  icon: 'download'
  color: 'blue'
